In [6]:
import pandas as pd
import numpy as np
import random
import string

In [22]:
# get rid of commas in songs
df = pd.read_csv("../data/spotify_songs_full.csv", index_col=0,delimiter=",").sample(frac=1)
df['artists'] = df['artists'].apply(lambda x: str(x).replace(";","-"))
df['track_name'] = df['track_name'].apply(lambda x: str(x).replace(",","-"))
df['album_name'] = df['album_name'].apply(lambda x: str(x).replace(",","-"))
df.to_csv("../data/spotify_songs_full_preproc.csv")
df.head()

In [41]:
# get rid of commas in artists
df = pd.read_csv("../data/spotify_artists.csv", index_col=0,delimiter=",").sample(frac=1)
df = df[df['Artist Name'] != "Artist"]
df['Lead Streams'] = df['Lead Streams'].apply(lambda x: x.replace(',','')[:-6])
df['Feats'] = df['Feats'].apply(lambda x: x.replace(',','')[:-6])
df['Tracks'] = df['Tracks'].apply(lambda x: x.replace(',',''))
df.to_csv("../data/spotify_artists_preproc.csv")
df.head()

,Artist Name,Lead Streams,Feats,Tracks,One Billion,100 Million,Last Updated
952,Evaluna Montaner,1495,133,46,0,4,31.07.22
620,Junior H,2190,300,104,0,5,12.09.22
733,Ghostemane,1897,68,140,0,3,19.08.22
366,Charli XCX,3464,,219,0,8,17.09.22
590,Cigarettes After Sex,2297,,30,0,6,30.08.22

In [4]:
df = pd.read_csv("../data/spotify_songs_full_preproc.csv", index_col=0,delimiter=",").sample(frac=1)
df = df.drop(['track_id','artists','album_name','key','mode','time_signature'],axis=1)
df.head()

,track_name,popularity,duration_ms,explicit,danceability,energy,loudness,speechiness,acousticness,instrumentalness,liveness,valence,tempo,track_genre
46765,Braindead Lunatic,18,200593,True,0.322,0.961,-0.719,0.3090,0.028000,0.000000,0.3730,0.185,205.029,happy
55561,Chaska,47,314226,False,0.832,0.822,-10.496,0.0565,0.506000,0.000002,0.2140,0.927,100.004,indian
109712,The Future Is The Past,39,283867,False,0.747,0.817,-9.034,0.0528,0.000114,0.809000,0.1060,0.331,126.041,techno
91051,Mary On A Cross,88,244804,False,0.466,0.900,-4.469,0.0447,0.000235,0.001040,0.1030,0.561,130.020,rock
77568,Ah! Como Eu Amei,45,194133,False,0.578,0.451,-13.806,0.0332,0.247000,0.000000,0.0823,0.280,128.360,pagode

In [8]:
# generate synthetic data
amount = 30000
genres = df['track_genre'].unique()
df_synth = pd.DataFrame()
df_synth['track_name'] = [random.choice(string.ascii_letters) for i in range(amount)]
df_synth['track_genre'] = [random.choice(genres) for i in range(amount)]
df_synth['duration_ms'] = [30000+int(random.random()*300000) for i in range(amount)]
df_synth['popularity'] = [int(random.random()*100) for i in range(amount)]
df_synth['danceability'] = [np.round(random.random(),3) for i in range(amount)]
df_synth['energy'] = [np.round(random.random(),3) for i in range(amount)]
df_synth['loudness'] = [np.round(random.random(),3) for i in range(amount)]
df_synth['speechiness'] = [np.round(random.random(),3) for i in range(amount)]
df_synth['acousticness'] = [np.round(random.random(),3) for i in range(amount)]
df_synth['instrumentalness'] = [np.round(random.random(),3) for i in range(amount)]
df_synth['liveness'] = [np.round(random.random(),3) for i in range(amount)]
df_synth['positivity'] = [np.round(random.random(),3) for i in range(amount)]
df_synth['explicit'] = [(random.random()>0.8) for i in range(amount)]
df_synth['tempo'] = [np.round(70+random.random()*70) for i in range(amount)]
df_synth.to_csv("spotify-song-stream.csv",header=False)
df_synth.head()

,track_name,track_genre,duration_ms,popularity,danceability,energy,loudness,speechiness,acousticness,instrumentalness,liveness,positivity,explicit,tempo
0,z,brazil,287930,82,0.638,0.380,0.273,0.365,0.159,0.457,0.270,0.142,False,110.0
1,D,sleep,83515,68,0.523,0.223,0.454,0.054,0.722,0.830,0.226,0.197,False,119.0
2,y,sad,207330,43,0.255,0.292,0.324,0.769,0.801,0.661,0.645,0.875,False,102.0
3,Q,ambient,323952,32,0.893,0.432,0.565,0.936,0.910,0.357,0.249,0.352,False,126.0
4,H,cantopop,176382,90,0.808,0.324,0.131,0.544,0.689,0.783,0.066,0.118,False,124.0