In [44]:
import pandas as pd
import numpy as np

N_SPLITS = 5

In [21]:
df = pd.read_csv("spotify_songs_full.csv", index_col=0,delimiter=",").sample(frac=1)
df_len = len(df)
split_len = int(np.floor(df_len/N_SPLITS))

In [22]:
df['artists'] = df['artists'].apply(lambda x: str(x).replace(";","-"))
df['track_name'] = df['track_name'].apply(lambda x: str(x).replace(",","-"))
df['album_name'] = df['album_name'].apply(lambda x: str(x).replace(",","-"))

In [24]:
df.to_csv("spotify_songs_full_preproc.csv")

In [20]:
for i in range(N_SPLITS):
    slice_name = "spotify-"+str(i+1)+".csv"
    df.iloc[(i*split_len):((i+1)*split_len)].to_csv("splits/"+slice_name)

In [21]:
df.describe()

,popularity,duration_ms,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature
count,114000.000000,1.140000e+05,114000.000000,114000.000000,114000.000000,114000.000000,114000.000000,114000.000000,114000.000000,114000.000000,114000.000000,114000.000000,114000.000000,114000.000000
mean,33.238535,2.280292e+05,0.566800,0.641383,5.309140,-8.258960,0.637553,0.084652,0.314910,0.156050,0.213553,0.474068,122.147837,3.904035
std,22.305078,1.072977e+05,0.173542,0.251529,3.559987,5.029337,0.480709,0.105732,0.332523,0.309555,0.190378,0.259261,29.978197,0.432621
min,0.000000,0.000000e+00,0.000000,0.000000,0.000000,-49.531000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,17.000000,1.740660e+05,0.456000,0.472000,2.000000,-10.013000,0.000000,0.035900,0.016900,0.000000,0.098000,0.260000,99.218750,4.000000
50%,35.000000,2.129060e+05,0.580000,0.685000,5.000000,-7.004000,1.000000,0.048900,0.169000,0.000042,0.132000,0.464000,122.017000,4.000000
75%,50.000000,2.615060e+05,0.695000,0.854000,8.000000,-5.003000,1.000000,0.084500,0.598000,0.049000,0.273000,0.683000,140.071000,4.000000
max,100.000000,5.237295e+06,0.985000,1.000000,11.000000,4.532000,1.000000,0.965000,0.996000,1.000000,1.000000,0.995000,243.372000,5.000000

In [41]:
df = pd.read_csv("spotify_artists.csv", index_col=0,delimiter=",").sample(frac=1)
df = df[df['Artist Name'] != "Artist"]
df['Lead Streams'] = df['Lead Streams'].apply(lambda x: x.replace(',','')[:-6])
df['Feats'] = df['Feats'].apply(lambda x: x.replace(',','')[:-6])
df['Tracks'] = df['Tracks'].apply(lambda x: x.replace(',',''))
df.head()

,Artist Name,Lead Streams,Feats,Tracks,One Billion,100 Million,Last Updated
952,Evaluna Montaner,1495,133,46,0,4,31.07.22
620,Junior H,2190,300,104,0,5,12.09.22
733,Ghostemane,1897,68,140,0,3,19.08.22
366,Charli XCX,3464,,219,0,8,17.09.22
590,Cigarettes After Sex,2297,,30,0,6,30.08.22

In [42]:
df.to_csv("spotify_artists_preproc.csv")

In [66]:
# generate artificial data
df = pd.read_csv("spotify_songs_full.csv", index_col=0,delimiter=",").sample(frac=1)
df = df.drop(['track_id','artists','album_name','key','mode','time_signature'],axis=1)
df.head()

array(['country', 'german', 'ska', 'kids', 'piano', 'latin', 'reggae',
       'trip-hop', 'sleep', 'heavy-metal', 'goth', 'indie', 'new-age',
       'j-idol', 'funk', 'idm', 'deep-house', 'death-metal', 'acoustic',
       'r-n-b', 'edm', 'dub', 'detroit-techno', 'psych-rock', 'punk-rock',
       'grunge', 'trance', 'dancehall', 'forro', 'hardcore', 'groove',
       'reggaeton', 'party', 'grindcore', 'opera', 'synth-pop', 'disney',
       'mpb', 'samba', 'sertanejo', 'alt-rock', 'chicago-house',
       'power-pop', 'electronic', 'emo', 'indie-pop', 'industrial',
       'alternative', 'j-dance', 'hardstyle', 'show-tunes', 'garage',
       'techno', 'club', 'guitar', 'electro', 'turkish', 'pop',
       'children', 'classical', 'house', 'rock-n-roll',
       'singer-songwriter', 'rock', 'breakbeat', 'j-rock', 'sad',
       'minimal-techno', 'gospel', 'j-pop', 'black-metal', 'world-music',
       'afrobeat', 'tango', 'romance', 'anime', 'pop-film', 'ambient',
       'metalcore', 'comedy', 'mandopop', 'french', 'chill', 'songwriter',
       'blues', 'hip-hop', 'metal', 'dance', 'iranian', 'disco', 'happy',
       'study', 'soul', 'swedish', 'salsa', 'brazil', 'honky-tonk',
       'cantopop', 'hard-rock', 'spanish', 'k-pop', 'folk', 'punk',
       'drum-and-bass', 'dubstep', 'british', 'pagode', 'jazz', 'malay',
       'rockabilly', 'latino', 'progressive-house', 'indian', 'bluegrass'],
      dtype=object)

In [73]:
import random
import string

amount = 30000
genres = df['track_genre'].unique()
df_synth = pd.DataFrame()
df_synth['track_name'] = [random.choice(string.ascii_letters) for i in range(amount)]
df_synth['track_genre'] = [random.choice(genres) for i in range(amount)]
df_synth['duration'] = [30000+int(random.random()*300000) for i in range(amount)]
df_synth['popularity'] = [int(random.random()*100) for i in range(amount)]
df_synth['dance'] = [np.round(random.random(),3) for i in range(amount)]
df_synth['energy'] = [np.round(random.random(),3) for i in range(amount)]
df_synth['loud'] = [np.round(random.random(),3) for i in range(amount)]
df_synth['speech'] = [np.round(random.random(),3) for i in range(amount)]
df_synth['acoustic'] = [np.round(random.random(),3) for i in range(amount)]
df_synth['instrument'] = [np.round(random.random(),3) for i in range(amount)]
df_synth['live'] = [np.round(random.random(),3) for i in range(amount)]
df_synth['positive'] = [np.round(random.random(),3) for i in range(amount)]
df_synth['tempo'] = [np.round(70+random.random()*70) for i in range(amount)]
df_synth.head()

,track_name,track_genre,duration,popularity,dance,energy,loud,speech,acoustic,instrument,live,positive,tempo
0,m,dub,313817,38,0.496,0.602,0.091,0.134,0.870,0.049,0.021,0.820,130.0
1,f,country,106984,73,0.072,0.124,0.907,0.350,0.850,0.584,0.511,0.287,94.0
2,P,sertanejo,181672,48,0.308,0.688,0.409,0.390,0.947,0.976,0.116,0.958,107.0
3,t,emo,249274,5,0.366,0.193,0.150,0.572,0.291,0.624,0.848,0.437,133.0
4,e,happy,282634,81,0.142,0.361,0.434,0.507,0.415,0.375,0.337,0.801,89.0

In [75]:
df_synth.to_csv("spotify-song-stream.csv",header=False)